# Site settings
title: "הגיגים של ינון"  # כותרת האתר
description: "בלוג אישי של ינון עם מחשבות והגיגים"  # תיאור קצר של האתר
baseurl: "/ynon"  # נדרש אם האתר לא יושב בתיקיית משנה
url: "https://amoszigller.github.io"  # כתובת ה-URL המלאה של האתר
author: "ינון"

# Build settings
markdown: kramdown
theme: minima  # ניתן לשנות את ערכת הנושא אם תרצה בעיצוב שונה
paginate: 5  # מספר הפוסטים בעמוד אחד

# Social Links (optional)
twitter_username: amoszigller  # קישור לטוויטר אם יש
github_username: amoszigller  # קישור לפרופיל GitHub שלך

# Plugins
plugins:
  - jekyll-feed  # יצירת RSS אוטומטית
  - jekyll-seo-tag  # תגי SEO אוטומטיים

# Include directories
include: ["_pages"]  # תוסיף את התיקייה הזו אם תרצה לכלול דפים מותאמים אישית

# Exclude files
exclude: ["Gemfile", "Gemfile.lock", "README.md", "LICENSE.md"]  # קבצים שלא יכללו בבניית האתר

# Custom settings
sass:
  style: compressed  # קומפרסיה של קבצי Sass אם יש
